### PR TITLE
Disable fuubar_auto_refresh by default

### LINKED ISSUE #108: `fuubar_auto_refresh` depends on gems loading order
## Current Behavior

In a project that uses both Fuubar and pry-byebug, the `fuubar_auto_refresh` config is set to `true`.

### Steps to Reproduce

1. Work in a project with a Gemfile that contains `fuubar` and `pry-byebug`.
2. Make `gem "fuubar"` appear before `gem "pry-byebug"` in `Gemfile`.
3. Add `binding.pry` to a spec.
4. Run the spec.
5. When it reaches the pry console, start typing, and notice that the Fuubar progress bar refreshes.
6. Ignoring the noisy refresh for a second, check the value of `RSpec.configuration.fuubar_auto_refresh`: it will be `true` whereas it is expected to be `false` in this context.

### Screenshot

image

## Expected Behavior

While I'm unsure whether there is a viable fix for this, the expected behavior would be that `RSpec.configuration.fuubar_auto_refresh` is `false` when it needs to be.

## Remarks

- I think commit 0cbd381bac7e920a0212f181ca7a5b65cba77c14 tried to fix the initial issue (#105), but that this fix is order-dependant.
- A quick-fix for me is to add `RSpec.configuration.fuubar_auto_refresh = false` in a RSpec support file (eg. `spec/support/fuubar.rb`).

### PR DESCRIPTION
**Pull request by davidstosik**
Fixes #108.

_Initially, this PR meant to improve the workaround for `fuubar_auto_refresh` not to bother Pry. After discussing with @jfelchner (below here), it looks like a saner option is just to keep `fuubar_auto_refresh` disabled by default and let the user enable it. See original description in the hidden block below._

<details>
<summary>Stop auto refresh when a Pry session starts</summary>

The problem with #105 was that the Pry-related code was running as soon
as the `fuubar` gem got loaded, which can be before `Pry` is defined (if
the `pry` gem gets loaded later).

Why This Change Is Necessary
--------------------------------------------------------------------------------

- [x] Bug Fix (see #108)
- [ ] New Feature

How These Changes Address the Issue
--------------------------------------------------------------------------------
In the changes I propose here,

- the Pry hooks are added later in the process, only when Fuubar starts,
which allows:
  - making sure all the gems in the Gemfile were loaded before
  testing the presence of `Pry`
  - avoiding to add Pry hooks if the Fuubar output is not used (eg. I
usually use Fuubar, but sometimes run `rspec --format documentation`)
- I used :before_session and :after_session hooks, allowing Fuubar to
keep refreshing as long as no Pry session is started

Side Effects Caused By This Change
--------------------------------------------------------------------------------

- [ ] This Causes a Breaking Change
- [x] This Does Not Cause Any Known Side Effects

Not a side-effect, but a know limitation: if the `pry` gem is added to
the Gemfile with the option `require: false`, then required too late
for Fuubar to know, then the hooks will not be added, and auto-refresh
will keep happening when the Pry session opens. For example:
```rb
# in Gemfile
gem "pry", require: false
gem "pry-byebug", require: false

# in spec/whatever_spec.rb
it "works" do
  # test something...

  require "pry-byebug"
  binding.pry
end
```

Checklist:
--------------------------------------------------------------------------------

- [ ] I have run `rubocop` against the codebase
  There seems to be an issue with Rubocop:
    > Error: invalid EnforcedStyle 'normal' for Layout/EmptyLinesAroundAccessModifier found in .rubocop_core.yml 
    > Valid choices are: around, only_before
- [ ] I have added tests to cover my changes
  There are no tests related to Pry. I would like to add some, but don't know how to start. Happy to add some if I can get help getting started.
- [ ] All new and existing tests passed

</details>

### CODE REVIEW

**Comment by jfelchner** [comment]
@davidstosik thanks for the PR but to be honest I don't like having any of this stuff relating to other gems in the code.  If you use a debugger workflow, it'd probably be best just to turn off auto-refresh in one of your spec support files.

What I think I'm going to do is to remove the Pry code and then set `auto_refresh` to `false` and make it an "opt in" situation.  As much as I like auto-refresh, I don't want to break people's workflows.

**Comment by davidstosik** [comment]
Thank you @jfelchner. I think making `auto_refresh` an opt-in behavior is a nice alternative.

**Comment by davidstosik** [comment]
@jfelchner I changed this PR approach to disable `fuubar_auto_refresh` by default, as discussed above, and updated the documentation as well. Please let me know what you think! 🙏

**Comment by jfelchner** [comment]
@davidstosik this is fantastic.  Thank you. 💖

**Comment by geoguide** [comment]
Is this going to get merged? Alternatively is there a way to disable auto_refresh when using the command line?

**Comment by jfelchner** [comment]
My bad everyone.  I completely forgot about this.  I'll get this in this weekend.

**Comment by kfrz** [comment]
:clap: Nice one @davidstosik - look forward to having this merged!

The CI is failing for `ruby-2.5.0`, complaining it can't find `bundler`, other 2.0+ rubies are :green_heart:!

**Comment by jfelchner** [comment]
Merged in d9304a4

**Pull request closed without merging**
