### PR TITLE
Slow spec reporting with configurable thresholds

### PR DESCRIPTION
**Pull request by PatrickTulskie**
I had a fast-failing progress bar RSpec formatter back in the Rails 2.x days that had slow spec reporting.  I really missed it... so I rebuilt it for fuubar.

I've never written specs for an RSpec formatter before so I hope I did an acceptable job there.  It was somewhat tricky.

I did notice that in a lot of places `example_passed` was being called with an `example` but in the RSpec docs, it looks like it's actually receiving a `notification`.  This was only an actual issue when trying to output information about the slow specs but I updated the rest of the specs for consistency.

All the specs still pass and it looks good.  I added some information to the readme about how to configure it.  Please let me know if this needs anything else.

### CODE REVIEW

**Comment by jfelchner** [comment]
@PatrickTulskie I think this is an interesting idea, however RSpec already has its option to show the slowest tests.  I'm concerned about adding more complexity to fuubar.  As it stands it is _extremely_ simple and that means very few bugs.  A lot of people rely on this gem because it is rock solid.

For example, have we tested this with gems that manipulate time like Timecop?  Does that affect calling `Time.now` in fuubar?  My guess would be yes.

**Comment by PatrickTulskie** [comment]
I've never worked with Timecop but I'm assuming that anything that messes with built in Ruby classes would have side effects on any other library that utilizes it.

As far as reliability goes - I've been using my fork of the gem in several complex test suites since before I opened the PR so I'm reasonably confident that it will work for most people.

I took a quick look through the code for profiling in `rspec-core` and it looks like they modify `Time` so as to get around issues with some libraries modifying `Time.now`.  I wouldn't mind borrowing this approach to alleviate the potential for issues you described.  I'll get up to date with master, tweak things, and bump the PR.

**Comment by PatrickTulskie** [comment]
Weird... github closed the branch. Re-opened it with cleaned up history.

**Comment by ojab** [comment]
AFAIU it can be done as a separate formatter (like ProfileFormatter from rspec-core, since RSpec [support multiple formatters simultaneously](https://relishapp.com/rspec/rspec-core/v/3-4/docs/command-line/format-option#multiple-formats-and-output-targets) ) or [even better] included into ProfileFormatter itself, so it can be used w/ any formatter for progress.

**Comment by PatrickTulskie** [comment]
@ojab Sure I can certainly do that. Fuubar was based on a compact progress bar formatter by Nick Evans but I figured the slow threshold bit hadn't been reimplemented yet.

If it was intentionally left out because the goal of the project changed or something then that's fine. I have no problem closing this out and simply doing my own thing.

**Comment by jfelchner** [comment]
@PatrickTulskie I appreciate the PR, but I feel like @ojab is right.  Back when this was originally in Fuubar, there was no way to run multiple formatters at the same time.  Now that that's the case, I feel like this would make a great formatter in its own right.  Let me know if you end up doing it.  I'll definitely use it! :)

**Pull request closed without merging**
