### PR TITLE
Show full progress bar if --tty option is passed

### PR DESCRIPTION
**Pull request by seven1m**
I use [observr](https://github.com/kevinburke/observr) to run my specs when files change. It runs `rspec --tty --format Fuubar` but ruby-progressbar still thinks there is no TTY, so it shows the dumbed-down progress bar.

This change makes it so passing the `--tty` option to rspec will force ruby-progressbar to think there is a TTY.

### CODE REVIEW

**Comment by seven1m** [comment]
It could be argued that this patch (adding `tty? => true` on `output`) belongs in [rspec-core](https://github.com/rspec/rspec-core), but I think the utility of it is further removed from that project and has a lesser chance of actually getting merged.

**Comment by seven1m** [comment]
I'm unsubscribing from this PR to get it off my list. If you have any questions, please @-mention me.

**Comment by jfelchner** [comment]
@seven1m I pinged the rspec-core team about this.  In the meantime, I'm going to add your patch because I think the functionality you're describing is a reasonable assumption.

**Comment by jfelchner** [comment]
@seven1m I committed a fix for this.  It's different from your solution because I didn't want to modify the object that RSpec gives us.  I'm going to release a beta version of `fuubar` in a second.  Give it a try and let me know if it works for you.

Thanks for reporting this!

**Comment by seven1m** [comment]
Great, thanks!!!

**Comment by jfelchner** [comment]
@seven1m for the record I'm not 100% sure I'm leaving this in here.  It's kind of hacky, but we can try it with the beta and see how it goes. :)

**Comment by seven1m** [comment]
I might have done something wrong, but I'm getting `cannot load such file -- fuubar/output (LoadError)` with 2.1.0.beta2 😢 

```
/usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- fuubar/output (LoadError)
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fuubar-2.1.0.beta2/lib/fuubar.rb:4:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by seven1m** [comment]
Not sure if it matters, but here is the command I'm running:

```
bundle exec spring rspec --color --tty  --require /usr/local/opt/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fuubar-2.1.0.beta2/lib/fuubar.rb --format Fuubar my_spec.rb
```

The reason I'm requiring the library manually is because the gem is not in my bundle (and I don't want it to be).

**Comment by seven1m** [comment]
Nevermind! I'm dumb. Works great!

**Pull request closed without merging**
